# Generated by Django 4.1.1 on 2022-09-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'db_table': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Emploees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploees.function')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploees.person', unique=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Сотрудники',
            },
        ),
    ]
