# Generated by Django 4.1.1 on 2022-09-16 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emploees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploees',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emploees.function'),
        ),
        migrations.AlterField(
            model_name='emploees',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emploees.person'),
        ),
    ]
